{{ range .packages.darwin.taps -}}
{{ if eq (kindOf .) "map" -}}
{{ if or (not (index . "when")) (has $.hosttype (index . "when")) -}}
tap {{ .name | quote }}
{{ end -}}
{{ else -}}
tap {{ . | quote }}
{{ end -}}
{{ end -}}
{{ range .packages.darwin.brews -}}
{{ if eq (kindOf .) "map" -}}
{{ if or (not (index . "when")) (has $.hosttype (index . "when")) -}}
brew {{ .name | quote }}
{{- range $key, $value := . -}}
{{- if eq $key "link" }}, link: {{ $value }}{{ end -}}
{{- if eq $key "restart_service" }}, restart_service: {{ $value }}{{ end -}}
{{- if eq $key "args" }}, args: {{ $value | toJson }}{{ end -}}
{{ end }}
{{ end -}}
{{ else -}}
brew {{ . | quote }}
{{ end -}}
{{ end -}}
{{ range .packages.darwin.casks -}}
{{ if eq (kindOf .) "map" -}}
{{ if or (not (index . "when")) (has $.hosttype (index . "when")) -}}
cask {{ .name | quote }}
{{ end -}}
{{ else -}}
cask {{ . | quote }}
{{ end -}}
{{ end -}}
{{ range .packages.darwin.mas -}}
{{ if or (not (index . "when")) (has $.hosttype (index . "when")) -}}
mas {{ .name | quote }}, id: {{ .id }}
{{ end -}}
{{ end -}}
