{{ range .packages.darwin.taps -}}
{{ if eq (kindOf .) "map" -}}
{{- $enabled := true -}}
{{- if hasKey . "when" -}}
  {{- $when := index . "when" -}}
  {{- if eq (kindOf $when) "slice" -}}
    {{- $enabled = has $.hosttype $when -}}
  {{- else -}}
    {{- $hosttypeOk := includeTemplate "when/check" (dict "item" . "key" "hosttype" "value" $.hosttype) | fromJson -}}
    {{- $deviceTypeOk := includeTemplate "when/check" (dict "item" . "key" "device_type" "value" $.device_type) | fromJson -}}
    {{- $hostEnvOk := includeTemplate "when/check" (dict "item" . "key" "host_env" "value" $.host_env) | fromJson -}}
    {{- $rolesOk := includeTemplate "when/check" (dict "item" . "key" "roles" "value" $.roles) | fromJson -}}
    {{- $enabled = and $hosttypeOk $deviceTypeOk $hostEnvOk $rolesOk -}}
  {{- end -}}
{{- end -}}
{{ if $enabled -}}
tap {{ .name | quote }}
{{ end -}}
{{ else -}}
tap {{ . | quote }}
{{ end -}}
{{ end -}}
{{ range .packages.darwin.brews -}}
{{ if eq (kindOf .) "map" -}}
{{- $enabled := true -}}
{{- if hasKey . "when" -}}
  {{- $when := index . "when" -}}
  {{- if eq (kindOf $when) "slice" -}}
    {{- $enabled = has $.hosttype $when -}}
  {{- else -}}
    {{- $hosttypeOk := includeTemplate "when/check" (dict "item" . "key" "hosttype" "value" $.hosttype) | fromJson -}}
    {{- $deviceTypeOk := includeTemplate "when/check" (dict "item" . "key" "device_type" "value" $.device_type) | fromJson -}}
    {{- $hostEnvOk := includeTemplate "when/check" (dict "item" . "key" "host_env" "value" $.host_env) | fromJson -}}
    {{- $rolesOk := includeTemplate "when/check" (dict "item" . "key" "roles" "value" $.roles) | fromJson -}}
    {{- $enabled = and $hosttypeOk $deviceTypeOk $hostEnvOk $rolesOk -}}
  {{- end -}}
{{- end -}}
{{ if $enabled -}}
brew {{ .name | quote }}
{{- range $key, $value := . -}}
{{- if eq $key "link" }}, link: {{ $value }}{{ end -}}
{{- if eq $key "restart_service" }}, restart_service: {{ $value }}{{ end -}}
{{- if eq $key "args" }}, args: {{ $value | toJson }}{{ end -}}
{{ end }}
{{ end -}}
{{ else -}}
brew {{ . | quote }}
{{ end -}}
{{ end -}}
{{ range .packages.darwin.casks -}}
{{ if eq (kindOf .) "map" -}}
{{- $enabled := true -}}
{{- if hasKey . "when" -}}
  {{- $when := index . "when" -}}
  {{- if eq (kindOf $when) "slice" -}}
    {{- $enabled = has $.hosttype $when -}}
  {{- else -}}
    {{- $hosttypeOk := includeTemplate "when/check" (dict "item" . "key" "hosttype" "value" $.hosttype) | fromJson -}}
    {{- $deviceTypeOk := includeTemplate "when/check" (dict "item" . "key" "device_type" "value" $.device_type) | fromJson -}}
    {{- $hostEnvOk := includeTemplate "when/check" (dict "item" . "key" "host_env" "value" $.host_env) | fromJson -}}
    {{- $rolesOk := includeTemplate "when/check" (dict "item" . "key" "roles" "value" $.roles) | fromJson -}}
    {{- $enabled = and $hosttypeOk $deviceTypeOk $hostEnvOk $rolesOk -}}
  {{- end -}}
{{- end -}}
{{ if $enabled -}}
cask {{ .name | quote }}
{{ end -}}
{{ else -}}
cask {{ . | quote }}
{{ end -}}
{{ end -}}
{{ range .packages.darwin.mas -}}
{{- $enabled := true -}}
{{- if hasKey . "when" -}}
  {{- $when := index . "when" -}}
  {{- if eq (kindOf $when) "slice" -}}
    {{- $enabled = has $.hosttype $when -}}
  {{- else -}}
    {{- $hosttypeOk := includeTemplate "when/check" (dict "item" . "key" "hosttype" "value" $.hosttype) | fromJson -}}
    {{- $deviceTypeOk := includeTemplate "when/check" (dict "item" . "key" "device_type" "value" $.device_type) | fromJson -}}
    {{- $hostEnvOk := includeTemplate "when/check" (dict "item" . "key" "host_env" "value" $.host_env) | fromJson -}}
    {{- $rolesOk := includeTemplate "when/check" (dict "item" . "key" "roles" "value" $.roles) | fromJson -}}
    {{- $enabled = and $hosttypeOk $deviceTypeOk $hostEnvOk $rolesOk -}}
  {{- end -}}
{{- end -}}
{{ if $enabled -}}
mas {{ .name | quote }}, id: {{ .id }}
{{ end -}}
{{ end -}}
