[packages.darwin]
taps = [
  "beeftornado/rmtree",
  "d12frosted/emacs-plus",
  "homebrew/bundle",
  "homebrew/command-not-found",
  "homebrew/services",
  "jimeh/emacs-builds",
  "railwaycat/emacsmacport",
]
brews = [
  "agg",
  "antidote",
  "apktool",
  "asciinema",
  "aspell",
  "autorestic",
  "beancount-language-server",
  "bfg",
  "block-goose-cli",
  "btop",
  "byobu",
  "chezmoi",
  "cmake",
  "coreutils",
  "curl",
  "dasel",
  "dbus",
  "deb-sig/tap/double-entry-generator",
  "docx2txt",
  "dprint",
  "exiftool",
  "fd",
  "ffmpegthumbnailer",
  "fzf",
  "gcc",
  "gh",
  "git",
  "git-lfs",
  "github-mcp-server",
  "gitwatch",
  "gnupg",
  "go",
  "graphviz",
  "helix",
  "hidapi",
  "htop",
  "hugo",
  "imagemagick",
  "iperf3",
  "isync",
  "jadx",
  "jdtls",
  "jq",
  "kotlin-language-server",
  "ktlint",
  "lefthook",
  "libgccjit",
  "libvterm",
  "logrotate",
  "markdown",
  "mas",
  "media-info",
  "mosh",
  "mosquitto",
  "mpv",
  "mu",
  "mupdf",
  "neovim",
  "node",
  "ocrmypdf",
  "openapi-generator",
  "p7zip",
  "pandoc",
  "pass",
  "pass-otp",
  "pdfcpu",
  "pgformatter",
  "pinentry-mac",
  "plantuml",
  "podman",
  "podman-compose",
  "podman-tui",
  "poppler",
  "portaudio",
  "python",
  "qpdf",
  "radare2",
  "rclone",
  "ripgrep",
  "rsync",
  "rust",
  "rustup",
  "samba",
  "scrcpy",
  "sdcv",
  "sshpass",
  "starship",
  "stylua",
  "swagger-codegen",
  "switchaudio-osx",
  "telnet",
  "tesseract",
  "tesseract-lang",
  "testssl",
  "tlrc",
  "tmux",
  "tokei",
  "tree-sitter",
  "uv",
  "wget",
  "xray",
  "zbar",
  "zig",
  "zsh",
  "zsh-autosuggestions",
  "zsh-syntax-highlighting",
  { name = "sleepwatcher", restart_service = true },
  { name = "atlassian/homebrew-acli/acli", when = "work" },
]
casks = [
  "amazon-q",
  "android-studio",
  "anki",
  "appcleaner",
  "betterdisplay",
  "bilibili",
  "blackhole-16ch",
  "blender",
  "block-goose",
  "chatgpt",
  "deepl",
  "discord",
  "emacs-app",
  "figma",
  "firefox",
  "folo",
  "font-cascadia-code",
  "font-dejavu",
  "font-fira-code",
  "font-google-sans-code",
  "font-ibm-plex-math",
  "font-ibm-plex-mono",
  "font-ibm-plex-sans",
  "font-ibm-plex-sans-sc",
  "font-inter",
  "font-iosevka",
  "font-iosevka-aile",
  "font-iosevka-etoile",
  "font-jetbrains-mono",
  "font-lxgw-wenkai",
  "font-maple-mono",
  "font-maple-mono-cn",
  "font-newsreader",
  "font-noto-sans",
  "font-noto-sans-math",
  "font-noto-sans-tai-viet",
  "font-noto-serif",
  "font-roboto",
  "font-roboto-mono",
  "font-roboto-serif",
  "font-roboto-slab",
  "font-sf-mono",
  "font-sf-pro",
  "font-symbols-only-nerd-font",
  "font-victor-mono",
  "fontgoggles",
  "ghostty",
  "iina",
  "itsycal",
  "jordanbaird-ice",
  "karabiner-elements",
  "libreoffice",
  "logseq",
  "loop",
  "lyricsx",
  "mactex-no-gui",
  "microsoft-edge",
  "mitmproxy",
  "monitorcontrol",
  "motrix",
  "neovide-app",
  "neteasemusic",
  "netnewswire",
  "nextcloud",
  "notion",
  "obsidian",
  "podman-desktop",
  "postman",
  "raspberry-pi-imager",
  "raycast",
  "sf-symbols",
  "shortcat",
  "spotify",
  "squirrel-app",
  "stats",
  "visual-studio-code",
  "wezterm",
  "windows-app",
  "wireshark-app",
  "xquartz",
  "zed",
  "zotero",
  { name = "1password", when = "work" },
  { name = "1password-cli", when = "work" },
  { name = "cursor", when = "work" },
  { name = "insta360-studio", when = "home" },
  { name = "intellij-idea", when = "work" },
  { name = "intune-company-portal", when = "work" },
  { name = "microsoft-auto-update", when = "work" },
  { name = "microsoft-teams", when = "work" },
  { name = "miro", when = "work" },
  { name = "mongodb-compass", when = "work" },
  { name = "mos", when = "home" },
  { name = "pycharm", when = "work" },
  { name = "signal", when = "home" },
  { name = "slack", when = "work" },
  { name = "steam", when = "home" },
  { name = "wechat", when = "home" },
  { name = "wechatwork", when = "work" },
]

[packages.darwin.mas]
"Amphetamine" = 937984704
"Developer" = 640199958
"Final Cut Pro" = 424389933
"Immersive Translate" = 6447957425
"Juice" = 1478610778
"Kindle" = 302584613
"Logic Pro" = 634148309
"MainStage" = 634159523
"MenubarX" = 1575588022
"Playgrounds" = 1496833156
"RSSHub Radar" = 1610744717
"The Unarchiver" = 425424353
"Unsplash Wallpapers" = 1284863847
"Xcode" = 497799835
