[packages.node]
global = [
  "@anthropic-ai/claude-code",
  "@google/gemini-cli",
  "@mermaid-js/mermaid-cli",
  "@openai/codex",
  "@prettier/plugin-ruby",
  "prettier",
  "puppeteer",
  "pyright",
  "typescript-language-server",
  "vscode-json-languageserver",
]
