[packages.node]
global = [
  "@google/gemini-cli",
  "@mermaid-js/mermaid-cli",
  "@openai/codex",
  "prettier",
  "puppeteer",
  "pyright",
  "typescript-language-server",
  "vscode-json-languageserver",
]
