[path]
org = "Developer/Personal/org"
org-roam = "Developer/Personal/org-roam"
beancount = "Developer/Personal/beancount"
blog = "Developer/Personal/blog"
nutstore = "Nutstore"

bin = "bin"
bun = ".bun"
emacs = ".config/emacs"
emacs-site-lisp = ".local/share/emacs/site-lisp"
isyncrc = ".config/isyncrc"
mail = ".maildir"
plum = ".config/plum"
proxy = ".config/proxy"
raycast = ".config/raycast"
sdkman = ".sdkman"

rime = ".local/share/rime"
rime-sync = "Nutstore/RimeSync"
squirrel = "/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel"
