[path]
[path.personal]
pass = ".password-store"
beancount = "Developer/Personal/beancount"
proxy = "Developer/Personal/proxy"
keyboard = "Developer/Personal/keyboard"
emacs = ".config/emacs"
org = "Developer/Personal/org"
org-roam = "Developer/Personal/org-roam"
blog = "Developer/Personal/blog"
skills = "Developer/Personal/skills"

[path.workspace]
aa = "Developer/AssaAbloy"
asahiart = "Developer/AsahiArt"
iv = "Developer/InfinityValley"
xz = "Developer/XingZhi"
qmk = "Developer/Example/QMK"

[path.tool]
bun = ".bun"
emacs-site-lisp = ".local/share/emacs/site-lisp"
isyncrc = ".config/isyncrc"
plum = ".config/plum"
raycast = ".config/raycast"
sdkman = ".sdkman"

[path.data]
nutstore = "Nutstore"
mail = ".maildir"
rime = ".local/share/rime"
rime-sync = "Nutstore/RimeSync"
squirrel = "Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel"
zotero-ext = "Profiles/Misaka/extensions"

[path.cache]
models-dev-api = ".cache/llm/data-set/models-dev.json"
iv-default-models-api = ".cache/llm/models/iv-default.json"
iv-codex-models-api = ".cache/llm/models/iv-codex.json"
iv-cc-models-api = ".cache/llm/models/iv-cc.json"
openai-models-api = ".cache/llm/models/openai.json"
google-models-api = ".cache/llm/models/google.json"
ollama-models-api = ".cache/llm/models/ollama.json"
opencode-models-api = ".cache/llm/models/opencode.json"
opencode-go-models-api = ".cache/llm/models/opencode-go.json"
openrouter-models-api = ".cache/llm/models/openrouter.json"
