[packages.python]
tools = [
  "beancount",
  "black",
  "fava",
  "git-filter-repo",
  "homeassistant-cli",
  "kimi-cli",
  "markitdown[all]",
  "my_cookies",
  "pylint",
  "python-lsp-server",
  "you-get",
  "yt-dlp[default]",
  { name = "aider-chat[help]", version = "3.12", with = "pip,playwright" },
  { name = "ansible", with-exec = "ansible-core,ansible-lint" },
  { name = "pyglossary", with = "prompt_toolkit,python-idzip,lxml" },
]
