[packages.python]
tools = [
  "beancount",
  "black",
  "fava",
  "git-filter-repo",
  "homeassistant-cli",
  "markitdown[all]",
  "pylint",
  "python-lsp-server",
  "you-get",
  "yt-dlp[default]",
  { name = "aider-chat[help]", version = "3.12", with = "pip,playwright" },
  { name = "ansible-core", with = "ansible" },
  { name = "pyglossary", with = "prompt_toolkit,python-idzip,lxml" },
]
