#!/bin/zsh

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Phoneshot
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 📱
# @raycast.packageName Android
# @raycast.argument1 { "type": "text", "placeholder": "Filename (optional)", "optional": true }

# Documentation:
# @raycast.author Misaka
# @raycast.authorURL https://github.com/chuxubank

save_dir="${PHONESHOT_DIR:-$HOME/Downloads}"
copy_to_clipboard="${PHONESHOT_COPY:-true}"
filename="${1:-phoneshot}"
out_file="${save_dir}/${filename}.png"

if ! adb get-state 1>/dev/null 2>&1; then
    echo "❌ No Android device found. Please connect your phone and enable USB debugging."
    exit 1
fi

adb shell screencap -p "/sdcard/${filename}.png"
adb pull "/sdcard/${filename}.png" "$out_file"
adb shell rm "/sdcard/${filename}.png"
echo "Saved phone screenshot to $out_file"

if [[ $copy_to_clipboard == true ]]; then
    clip-image "$out_file"
    echo "Copied screenshot to clipboard"
fi
