#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Send iMessage
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 💬
# @raycast.packageName IM
# @raycast.argument1 { "type": "text", "placeholder": "Buddy" }
# @raycast.argument2 { "type": "text", "placeholder": "Message" }

# Documentation:
# @raycast.description Send iMessage to given people
# @raycast.author Misaka
# @raycast.authorURL https://github.com/chuxubank

on run {targetBuddyPhone, targetMessage}
	tell application "Messages"
		set targetService to 1st account whose service type = iMessage
		set targetBuddy to participant targetBuddyPhone of targetService
		send targetMessage to targetBuddy
	end tell
end run
