#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Clip Picture File
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 📋
# @raycast.argument1 { "type": "text", "placeholder": "Full picture file name" }

# Documentation:
# @raycast.description Set the clipboard to a picture file
# @raycast.author Misaka
# @raycast.authorURL https://github.com/chuxubank

on run argv
  set the clipboard to (read (POSIX file (first item of argv)) as picture)
end run
