#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Clip File
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 📋
# @raycast.argument1 { "type": "text", "placeholder": "Full file name" }

# Documentation:
# @raycast.description Set the clipboard to a file
# @raycast.author Misaka
# @raycast.authorURL https://github.com/chuxubank

on run argv
  set the clipboard to (POSIX file (first item of argv))
end run
