[packages.apt]
pkg = [
  "aspell",
  "aspell-en",
  "cmake",
  "emacs",
  "fzf",
  "gh",
  "git",
  "git-lfs",
  "gnupg",
  "imagemagick",
  "isync",
  "jq",
  "libssl-dev",
  "logrotate",
  "nodejs",
  "npm",
  "pass",
  "pkg-config",
  "plantuml",
  "rclone",
  "ripgrep",
  "rsync",
  "rustup",
  "sshpass",
  "tmux",
  "wget",
  "zip",
  "zsh",
]
