[packages.darwin]
taps = [
  "achannarasappa/tap",
  "beeftornado/rmtree",
  "d12frosted/emacs-plus",
  "deb-sig/tap",
  "railwaycat/emacsmacport",
  "sikarugir-app/sikarugir",
  "steipete/tap",
  "theseal/ssh-askpass",
  "tw93/tap",
  { name = "atlassian/acli", when = ["aa"] },
]
brews = [
  "achannarasappa/tap/ticker",
  "agg",
  "antidote",
  "apktool",
  "asciinema",
  "aspell",
  "autorestic",
  "awk",
  "beancount-language-server",
  "bfg",
  "bind",
  "bison",
  "block-goose-cli",
  "btop",
  "chezmoi",
  "cmake",
  "coreutils",
  "curl",
  "dasel",
  "dbus",
  "deb-sig/tap/double-entry-generator",
  "docx2txt",
  "dprint",
  "exiftool",
  "fd",
  "ffmpegthumbnailer",
  "fzf",
  "gcc",
  "gh",
  "git",
  "git-lfs",
  "github-mcp-server",
  "gitwatch",
  "gnupg",
  "go",
  "graphviz",
  "grep",
  "helix",
  "hidapi",
  "htop",
  "hugo",
  "imagemagick",
  "iperf3",
  "isync",
  "jadx",
  "jdtls",
  "jq",
  "ktlint",
  "leetcode-cli",
  "lefthook",
  "libgccjit",
  "librime",
  "libvterm",
  "logrotate",
  "markdown",
  "mas",
  "media-info",
  "mosh",
  "mosquitto",
  "mpv",
  "mu",
  "mupdf",
  "neovim",
  "node",
  "ocrmypdf",
  "openapi-generator",
  "oxipng",
  "p7zip",
  "pandoc",
  "paperkey",
  "pass",
  "pass-git-helper",
  "pass-otp",
  "pdfcpu",
  "pgformatter",
  "pinentry-mac",
  "plantuml",
  "pngpaste",
  "pngquant",
  "poppler",
  "portaudio",
  "python",
  "qpdf",
  "radare2",
  "rclone",
  "reddix",
  "ripgrep",
  "rsync",
  "ruby",
  "rustup",
  "samba",
  "scrcpy",
  "sdcv",
  "shfmt",
  "sing-box",
  "socat",
  "sshpass",
  "starship",
  "steipete/tap/imsg",
  "stylua",
  "swagger-codegen",
  "switchaudio-osx",
  "telnet",
  "tesseract",
  "tesseract-lang",
  "testssl",
  "theseal/ssh-askpass/ssh-askpass",
  "tlrc",
  "tmux",
  "tokei",
  "tree-sitter",
  "tuios",
  "tw93/tap/mole",
  "uv",
  "watch",
  "wget",
  "xray",
  "yq",
  "zbar",
  "zellij",
  "zig",
  "zsh",
  "zsh-autosuggestions",
  "zsh-syntax-highlighting",
  { name = "atlassian/homebrew-acli/acli", when = ["aa"] },
  { name = "awscli", when = ["aa"] },
  { name = "cocoapods", when = ["home", "iv"] },
  { name = "podman", when = ["aa"] },
  { name = "podman-compose", when = ["aa"] },
  { name = "podman-tui", when = ["aa"] },
  { name = "sleepwatcher", restart_service = true },
]
casks = [
  "alma",
  "android-studio",
  "anki",
  "antigravity",
  "appcleaner",
  "basictex",
  "betterdisplay",
  "bilibili",
  "blackhole-16ch",
  "blender",
  "block-goose",
  "chatgpt",
  "chatgpt-atlas",
  "claude",
  "claude-code",
  "d12frosted/emacs-plus/emacs-plus-app",
  "deepl",
  "discord",
  "figma",
  "firefox",
  "folo",
  "font-cascadia-code",
  "font-dejavu",
  "font-fira-code",
  "font-google-sans-code",
  "font-ibm-plex-math",
  "font-ibm-plex-mono",
  "font-ibm-plex-sans",
  "font-ibm-plex-sans-sc",
  "font-inter",
  "font-iosevka",
  "font-iosevka-aile",
  "font-iosevka-etoile",
  "font-jetbrains-mono",
  "font-lxgw-wenkai",
  "font-maple-mono",
  "font-maple-mono-cn",
  "font-newsreader",
  "font-noto-sans",
  "font-noto-sans-math",
  "font-noto-sans-tai-viet",
  "font-noto-serif",
  "font-roboto",
  "font-roboto-mono",
  "font-roboto-serif",
  "font-roboto-slab",
  "font-sf-mono",
  "font-sf-pro",
  "font-symbols-only-nerd-font",
  "font-victor-mono",
  "fontgoggles",
  "ghostty",
  "iina",
  "inkscape",
  "itsycal",
  "jordanbaird-ice",
  "karabiner-elements",
  "kiro-cli",
  "libreoffice",
  "logseq",
  "loop",
  "lyricsx",
  "microsoft-edge",
  "mitmproxy",
  "monitorcontrol",
  "motrix",
  "neovide-app",
  "netnewswire",
  "nextcloud",
  "notion",
  "obsidian",
  "postman",
  "raspberry-pi-imager",
  "raycast",
  "sf-symbols",
  "shortcat",
  "squirrel-app",
  "stats",
  "steipete/tap/codexbar",
  "visual-studio-code",
  "wezterm",
  "windows-app",
  "wireshark-app",
  "xquartz",
  "zed",
  "zotero",
  { name = "1password", when = ["aa"] },
  { name = "1password-cli", when = ["aa"] },
  { name = "Sikarugir-App/sikarugir/sikarugir", when = ["home"] },
  { name = "battery", when = ["home"] },
  { name = "cursor", when = ["aa"] },
  { name = "feishu", when = ["iv"] },
  { name = "guitar-pro", when = ["home"] },
  { name = "home-assistant", when = ["home"] },
  { name = "insta360-studio", when = ["home"] },
  { name = "intellij-idea", when = ["aa"] },
  { name = "intune-company-portal", when = ["aa"] },
  { name = "microsoft-auto-update", when = ["aa"] },
  { name = "microsoft-teams", when = ["aa"] },
  { name = "miro", when = ["aa"] },
  { name = "mongodb-compass", when = ["aa"] },
  { name = "mos", when = ["home", "iv"] },
  { name = "neteasemusic", when = ["home"] },
  { name = "orbstack", when = ["home"] },
  { name = "podman-desktop", when = ["aa"] },
  { name = "pycharm", when = ["aa"] },
  { name = "signal", when = ["home"] },
  { name = "slack", when = ["aa"] },
  { name = "spotify", when = ["home"] },
  { name = "steam", when = ["home"] },
  { name = "tuxguitar", when = ["home"] },
  { name = "wechat", when = ["home"] },
  { name = "wechatwork", when = ["aa"] },
]
mas = [
  { id = 1284863847, name = "Unsplash Wallpapers" },
  { id = 1478610778, name = "Juice" },
  { id = 1496833156, name = "Playgrounds", when = ["home"] },
  { id = 1575588022, name = "MenubarX" },
  { id = 1610744717, name = "RSSHub Radar" },
  { id = 424389933, name = "Final Cut Pro", when = ["home"] },
  { id = 425424353, name = "The Unarchiver" },
  { id = 497799835, name = "Xcode" },
  { id = 634148309, name = "Logic Pro", when = ["home"] },
  { id = 634159523, name = "MainStage", when = ["home"] },
  { id = 640199958, name = "Developer" },
  { id = 6447957425, name = "Immersive Translate" },
  { id = 937984704, name = "Amphetamine" },
]
