[packages.node]
global = [
  "@ansible/ansible-language-server",
  "@anthropic-ai/claude-code",
  "@blowmage/cursor-agent-acp",
  "@github/copilot-language-server",
  "@google/gemini-cli",
  "@mermaid-js/mermaid-cli",
  "@openai/codex",
  "@prettier/plugin-ruby",
  "@sourcegraph/amp",
  "@zed-industries/codex-acp",
  "add-skill",
  "bash-language-server",
  "graphql-language-service-cli",
  "prettier",
  "puppeteer",
  "pyright",
  "typescript-language-server",
  "vscode-json-languageserver",
  "yaml-language-server",
  { name = "emacs-lsp-proxy", trust = true },
  { name = "opencode-ai", trust = true },
]
