[packages.pacman]
core = [
  { name = "rclone", owner = "rclone" },
  "pass",
]
extra = [
  "librime",
  "starship",
  "wezterm",
  "zsh-autosuggestions",
  "zsh-syntax-highlighting",
]
aur = [
  "stably-orca-bin",
  "zsh-antidote",
]
