[packages.termux]
repo = [
  "x11-repo",
]
pkg = [
  "aspell",
  "aspell-en",
  "chezmoi",
  "cmake",
  "emacs-x",
  "fzf",
  "gh",
  "git",
  "git-lfs",
  "gnupg",
  "imagemagick",
  "isync",
  "jq",
  "librime",
  "libvterm",
  "logrotate",
  "mu",
  "nodejs",
  "pass",
  "pass-otp",
  "plantuml",
  { name = "rclone", owner = "rclone" },
  "ripgrep",
  "rsync",
  "rust",
  "sshpass",
  "starship",
  "termux-x11-nightly",
  "tmux",
  "tokei",
  "tree-sitter",
  "uv",
  "wget",
  "zip",
  "zsh",
]
