[packages.termux]
pkg = [
  "aspell",
  "chezmoi",
  "cmake",
  "fzf",
  "gh",
  "git",
  "gnupg",
  "imagemagick",
  "isync",
  "jq",
  "libvterm",
  "logrotate",
  "mu",
  "nodejs",
  "pandoc",
  "pass",
  "pass-otp",
  "plantuml",
  "rclone",
  "ripgrep",
  "rust",
  "sshpass",
  "starship",
  "tmux",
  "tokei",
  "tree-sitter",
  "uv",
  "wget",
  "zip",
  "zsh",
]
