name: CI

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v3

      - name: Cache chezmoi
        uses: actions/cache@v4
        with:
          path: ${{ env.HOME }}/.cache/chezmoi
          key: ${{ runner.os }}-chezmoi-${{ hashFiles('home/.chezmoi.toml.tmpl', 'home/.chezmoidata/**/*.toml') }}
          restore-keys: |
            ${{ runner.os }}-chezmoi-

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ${{ env.HOME }}/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('home/.chezmoidata/python_packages.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Cache apt
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/
          key: ${{ runner.os }}-apt-${{ hashFiles('home/.chezmoidata/apt_packages.toml') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Cache bun
        uses: actions/cache@v4
        with:
          path: ${{ env.HOME }}/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('home/.chezmoidata/node_packages.toml') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Cache sdkman
        uses: actions/cache@v4
        with:
          path: ${{ env.HOME }}/.sdkman
          key: ${{ runner.os }}-sdkman-${{ hashFiles('home/.chezmoidata/sdkman_packages.toml') }}
          restore-keys: |
            ${{ runner.os }}-sdkman-

      - run: ./install.sh

      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
