name: CI

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v6

      - name: Cache chezmoi
        uses: actions/cache@v5
        with:
          path: ~/.cache/chezmoi
          key: ${{ runner.os }}-chezmoi-${{ hashFiles('home/.chezmoi.toml.tmpl', 'home/.chezmoiexternals/**/*.toml.tmpl') }}
          restore-keys: |
            ${{ runner.os }}-chezmoi-

      - name: Cache sdkman
        uses: actions/cache@v5
        with:
          path: ~/.sdkman
          key: ${{ runner.os }}-sdkman-${{ hashFiles('home/.chezmoidata/packages/sdkman.toml') }}
          restore-keys: |
            ${{ runner.os }}-sdkman-

      - name: Cache rust
        uses: actions/cache@v5
        with:
          path: |
            ~/.local/share/cargo/bin/
            ~/.local/share/cargo/registry/index/
            ~/.local/share/cargo/registry/cache/
            ~/.local/share/cargo/git/db/
          key: ${{ runner.os }}-rust-${{ hashFiles('home/.chezmoidata/packages/rust.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-

      - name: Cache bun
        if: false
        uses: actions/cache@v5
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('home/.chezmoidata/packages/node.toml') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Cache uv
        if: false
        uses: actions/cache@v5
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('home/.chezmoidata/packages/python.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Run install
        run: ./install.sh

      - name: Chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
